[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# solc_version = "0.8.17" # I tell Foundry that the solidity compiler version to be
# optimizer = true # Enable the optimizer
# optimizer_runs = 200 # Number of runs for the optimizer


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
